---
- name: package test
  hosts: ubuntuvm
  become: true
  vars:
    cowsay_package_name: cowsay

  tasks:
  - name: Install cowsay
    ansible.builtin.apt:
      name: "{{ cowsay_package_name }}"
      state: present
      update_cache: true
